Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/mnt/production/user/george.antonopoulos/DEV/ffmpeg_convert/ffmpeg_ui.py", line 534, in run_ffmpeg
    input_type = self.input_type_var.get()
AttributeError: 'FFmpegUI' object has no attribute 'input_type_var'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/mnt/production/user/george.antonopoulos/DEV/ffmpeg_convert/ffmpeg_ui.py", line 534, in run_ffmpeg
    input_type = self.input_type_var.get()
AttributeError: 'FFmpegUI' object has no attribute 'input_type_var'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/mnt/production/user/george.antonopoulos/DEV/ffmpeg_convert/ffmpeg_ui.py", line 534, in run_ffmpeg
    input_type = self.input_type_var.get()
AttributeError: 'FFmpegUI' object has no attribute 'input_type_var'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/mnt/production/user/george.antonopoulos/DEV/ffmpeg_convert/ffmpeg_ui.py", line 534, in run_ffmpeg
    input_type = self.input_type_var.get()
AttributeError: 'FFmpegUI' object has no attribute 'input_type_var'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/mnt/production/user/george.antonopoulos/DEV/ffmpeg_convert/ffmpeg_ui.py", line 534, in run_ffmpeg
    input_type = self.input_type_var.get()
AttributeError: 'FFmpegUI' object has no attribute 'input_type_var'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/mnt/production/user/george.antonopoulos/DEV/ffmpeg_convert/ffmpeg_ui.py", line 534, in run_ffmpeg
    input_type = self.input_type_var.get()
AttributeError: 'FFmpegUI' object has no attribute 'input_type_var'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/mnt/production/user/george.antonopoulos/DEV/ffmpeg_convert/ffmpeg_ui.py", line 534, in run_ffmpeg
    input_type = self.input_type_var.get()
AttributeError: 'FFmpegUI' object has no attribute 'input_type_var'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/mnt/production/user/george.antonopoulos/DEV/ffmpeg_convert/ffmpeg_ui.py", line 534, in run_ffmpeg
    input_type = self.input_type_var.get()
AttributeError: 'FFmpegUI' object has no attribute 'input_type_var'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/mnt/production/user/george.antonopoulos/DEV/ffmpeg_convert/ffmpeg_ui.py", line 534, in run_ffmpeg
    input_type = self.input_type_var.get()
AttributeError: 'FFmpegUI' object has no attribute 'input_type_var'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/mnt/production/user/george.antonopoulos/DEV/ffmpeg_convert/ffmpeg_ui.py", line 534, in run_ffmpeg
    input_type = self.input_type_var.get()
AttributeError: 'FFmpegUI' object has no attribute 'input_type_var'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/mnt/production/user/george.antonopoulos/DEV/ffmpeg_convert/ffmpeg_ui.py", line 534, in run_ffmpeg
    input_type = self.input_type_var.get()
AttributeError: 'FFmpegUI' object has no attribute 'input_type_var'
